# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Channel' do
  
  #use_frameworks!

  # Pods for Channel-tvOS
  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  
  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

end
